system:
  device: gpu  # [cpu, gpu, tpu]

project:
  # name: protein-synformer-2048-lora
  # name: protein-synformer
  name: protein-synformer-optuna-trials

chem:
  fp_option:
    type: morgan
    morgan_radius: 2
    morgan_n_bits: 2048
  building_block_path: data/building_blocks/Enamine_Rush-Delivery_Building_Blocks-US_223244cmpd_20231001.sdf
  reaction_path: data/rxn_templates/comprehensive.txt
  rxn_matrix: data/processed/comp_2048/matrix.pkl
  fpindex: data/processed/comp_2048/fpindex.pkl
  # !!
  protein_molecule_pairs_train_path: data/protein_molecule_pairs/papyrus_train_155187.csv
  protein_molecule_pairs_val_path: data/protein_molecule_pairs/papyrus_val_19399.csv
  # protein_molecule_pairs_test_path: data/protein_molecule_pairs/papyrus_test_19399.csv
  protein_embedding_path: data/protein_embeddings/embeddings_selection_float16_4973.pth 
  synthetic_pathways_path: data/synthetic_pathways/filtered_pathways_370000.pth
  # !!

data:
  init_stack_weighted_ratio: 0.90

# TODO: use exactly those settings as sf_ed_default.ckpt
model:
  # !!
  encoder_type: protein 
  encoder:
    d_model: 768  # must be same as decoder.d_model
    d_protein: 1152  # ESM num embedding dimensions
  # !!
  decoder:
    d_model: 768
    nhead: 16
    dim_feedforward: 4096
    num_layers: 10
    pe_max_len: 32
    output_norm: false
    fingerprint_dim: ${chem.fp_option.morgan_n_bits}
    num_reaction_classes: 120
    lora: true
    lora_rank: 32 # Overwritten by Optuna when doing trials
  fingerprint_head_type: diffusion
  fingerprint_head:
    d_model: 768
    fingerprint_dim: ${chem.fp_option.morgan_n_bits}
    hidden_dim: 4096
    diffusion_steps: 100
    diffusion_s: 0.01

train:
  loss_weights:
    token: 1.0
    reaction: 1.0
    fingerprint_diffusion: 0.5
    fingerprint_bce: 0.0  # For monitoring purpose only
  val_loss_weights:
    token: 1.0
    reaction: 1.0
    fingerprint_diffusion: 0.0  # Multinomial diffusion loss does not drop
    fingerprint_bce: 0.5
  max_epochs: 2
  val_check_interval: 500
  max_grad_norm: 100.0
  optimizer:
    type: adamw
    lr: 3.e-4 # Overwritten by Optuna when doing trials
    weight_decay: 0 # Overwritten by Optuna when doing trials
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8 # Overwritten by Optuna when doing trials
    patience: 10 # Overwritten by Optuna when doing trials
    min_lr: 1.e-5 # Overwritten by Optuna when doing trials
